// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnziezjejfnnxvjwxcrc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuemllemplamZubnh2and4Y3JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NDI0ODQsImV4cCI6MjA2OTMxODQ4NH0.x2Jq8E8059adN7LQZfvxx0C5hNPGXy58blm_bwXfl3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});